#!/bin/bash
#PBS -N Flax100kOldTokenizer20k
#PBS -q gpus
#PBS -l select=1:ncpus=32:mem=100gb:ngpus=2:glist=a100
#PBS -l walltime=72:00:00
#PBS -m abe
#PBS -W group_list=x-ccast-prj-chayan

cd $PBS_O_WORKDIR

source ~/anaconda3/bin/activate flax

export HF_DATASETS_CACHE=$PWD/dataset

python run_t5_mlm_flax.py \
	--output_dir="./virusTrained100k" \
	--model_type="t5" \
	--config_name="./virusConfig" \
	--tokenizer_name="./virusTokenizer" \
	--train_file="/mmfs1/projects/changhui.yan/vishwajeet.marathe/virusTransformer/data/final/dataset100k/train.csv" \
	--validation_file="/mmfs1/projects/changhui.yan/vishwajeet.marathe/virusTransformer/data/final/dataset100k/validation.csv" \
	--max_seq_length="512" \
	--per_device_train_batch_size="32" \
	--per_device_eval_batch_size="32" \
	--adafactor \
	--learning_rate="0.005" \
	--weight_decay="0.001" \
	--warmup_steps="2000" \
	--overwrite_output_dir \
	--logging_steps="500" \
	--save_steps="10000" \
	--eval_steps="2500"

