#!/bin/bash
#PBS -q default
#PBS -N alignJob
##keep ncpus=1
#PBS -l select=1:mem=128gb:ncpus=16
#PBS -l walltime=24:00:00
##change "x-ccast-prj" to "x-ccast-prj-[your project group name: x-ccast-prj-chayan]"
#PBS -W group_list=x-ccast-prj-chayan

cd ${PBS_O_WORKDIR}

##this is for activating local environment
##/mmfs1/thunder/home/deewan.bajracharya/anaconda3/bin/activate tf-gpu is for Thunder
##replace it with /mmfs1/home/deewan.bajracharya/anaconda3/bin/activate tf-gpu for Thunder Prime
source ~/anaconda3/bin/activate flax_fine_tune 

# Name of the python script to run
python3 pairwise_align.py

